module.exports.descripters = [
    'Forest',
    'Ancient',
    'Petrified',
    'Roaring',
    'Cascade',
    'Tumbling',
    'Silent',
    'Redwood',
    'Bullfrog',
    'Maple',
    'Misty',
    'Elk',
    'Grizzle',
    'Ocean',
    'Sky',
    'Dusty',
    'Diamond',
]

module.exports.places = [
    'Flats',
    'Village',
    'Canyon',
    'Pond',
    'Group camp',
    'Horse camp',
    'Ghost Town',
    'Camp',
    'Dispersed camp',
    'Backcountry',
    'Backcountry',
    'River',
    'Creek',
    'Creekside',
    'Bay',
    'Spring',
    'Bayshore',
    'Sands',
    'Mule Camp',
    'Hunting Camp',
    'Cliffs',
    'Hollow',
]